AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-resume-challenge-iac

  Sample SAM Template for cloud-resume-challenge-iac

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  FrontEndBucketPolicy:
    UpdateReplacePolicy: Delete
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Delete
    Properties:
      Bucket: !Ref FrontEndBucket
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Condition:
              StringEquals:
                AWS:SourceArn: 
                  Fn::Join:
                   - ''
                   - - 'arn:aws:cloudfront::'
                     - !Ref 'AWS::AccountId'
                     - ':distribution/'
                     - !Ref CloudFrontDistribution
            Resource: arn:aws:s3:::tristantech.org-iac/*
            Action: s3:GetObject
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Sid: AllowCloudFrontServicePrincipal
        Id: PolicyForCloudFrontPrivateContent

  FrontEndBucket:
    UpdateReplacePolicy: Delete
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
      BucketName: tristantech.org-iac
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      #WebsiteConfiguration:
        #IndexDocument: index.html 
      #LoggingConfiguration:
        #TargetObjectKeyFormat:
          #PartitionedPrefix:
            #PartitionDateSource: EventTime
        #DestinationBucketName: logs.tristantech.org
        #LogFilePrefix: logs/

  CloudFrontCachePolicy:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CloudFront::CachePolicy"
    DeletionPolicy: "Delete"
    Properties:
      CachePolicyConfig:
        Comment: "Policy with caching enabled. Supports Gzip and Brotli compression."
        MinTTL: 1
        MaxTTL: 3.1536E7
        ParametersInCacheKeyAndForwardedToOrigin:
          QueryStringsConfig:
            QueryStringBehavior: "none"
          EnableAcceptEncodingBrotli: true
          HeadersConfig:
            HeaderBehavior: "none"
          CookiesConfig:
            CookieBehavior: "none"
          EnableAcceptEncodingGzip: true
        DefaultTTL: 86400
        Name: "Custom-CachingOptimized"

  CloudFrontDistribution:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CloudFront::Distribution"
    DeletionPolicy: "Delete"
    Properties:
      DistributionConfig:
        Logging:
          IncludeCookies: false
          Bucket: ""
          Prefix: ""
        Comment: ""
        DefaultRootObject: "index.html"
        Origins:
        - ConnectionTimeout: 10
          OriginAccessControlId:
            Ref: "CloudFrontOriginAccessControl"
          ConnectionAttempts: 3
          OriginCustomHeaders: []
          DomainName:
            Fn::GetAtt:
            - "FrontEndBucket"
            - "RegionalDomainName"
          OriginShield:
            Enabled: false
          S3OriginConfig:
            OriginAccessIdentity: ""
          OriginPath: ""
          Id: "tristantech.org-iac"
        ViewerCertificate:
          MinimumProtocolVersion: "TLSv1.2_2021"
          SslSupportMethod: "sni-only"
          AcmCertificateArn: "arn:aws:acm:us-east-1:912311480070:certificate/80bf7507-ed8a-4de8-b7eb-56ef0c286e42"
        PriceClass: "PriceClass_100"
        DefaultCacheBehavior:
          Compress: true
          FunctionAssociations: []
          LambdaFunctionAssociations: []
          TargetOriginId: "tristantech.org-iac"
          ViewerProtocolPolicy: "redirect-to-https"
          GrpcConfig:
            Enabled: false
          TrustedSigners: []
          FieldLevelEncryptionId: ""
          TrustedKeyGroups: []
          AllowedMethods:
          - "HEAD"
          - "GET"
          CachedMethods:
          - "HEAD"
          - "GET"
          SmoothStreaming: false
          CachePolicyId:
            Ref: "CloudFrontCachePolicy"
        Staging: false
        CustomErrorResponses:
        - ErrorCachingMinTTL: 10
          ResponseCode: 403
          ErrorCode: 403
          ResponsePagePath: "/error-pages/403.html"
        - ErrorCachingMinTTL: 10
          ResponseCode: 404
          ErrorCode: 404
          ResponsePagePath: "/error-pages/404.html"
        ContinuousDeploymentPolicyId: ""
        OriginGroups:
          Quantity: 0
          Items: []
        Enabled: true
        Aliases:
        - "tristantech.org"
        - "www.tristantech.org"
        IPV6Enabled: true
        WebACLId: "arn:aws:wafv2:us-east-1:912311480070:global/webacl/CreatedByCloudFront-891b1432-5997-49e0-855f-bb709f051c9d/25a6a306-4657-4b01-8950-fe03f500012a"
        HttpVersion: "http2"
        Restrictions:
          GeoRestriction:
            Locations: []
            RestrictionType: "none"
        CacheBehaviors: []

  CloudFrontOriginAccessControl:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CloudFront::OriginAccessControl"
    DeletionPolicy: "Delete"
    Properties:
      OriginAccessControlConfig:
        SigningBehavior: "always"
        Description: ""
        SigningProtocol: "sigv4"
        OriginAccessControlOriginType: "s3"
        Name: "${FrontEndBucket}.s3.eu-central-1.amazonaws.com"

    
  myDNS:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: Z00273233K0LGAJK7OZOH
      RecordSets:
        - Name: tristantech.org
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt 
              - CloudFrontDistribution
              - DomainName
        - Name: www.tristantech.org
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt 
            - CloudFrontDistribution
            - DomainName

#Resources:
  #FrontEndBucket:
    #Type: 'AWS::S3::Bucket'
    #Properties:
      #BucketName: tristantech.org-iac
      #PublicAccessBlockConfiguration:
        #BlockPublicAcls: false
        #BlockPublicPolicy: false
        #IgnorePublicAcls: false
        #RestrictPublicBuckets: false
      #WebsiteConfiguration:
        #IndexDocument: index.html
        
  #FrontEndBucketPolicy:
    #UpdateReplacePolicy: Delete
    #Type: 'AWS::S3::BucketPolicy'
    #DeletionPolicy: Delete
    #Properties:
      #Bucket: !Ref FrontEndBucket
      #PolicyDocument:
        #Version: '2012-10-17'
        #Statement:
          #- Sid: PublicReadForGetBucketObjects
            #Effect: Allow
            #Principal: '*'
            #Action: 's3:GetObject'
            #Resource:
              #Fn::Join:
                #- ''
                #- - 'arn:aws:s3:::'
                  #- Ref: 'FrontEndBucket'
                  #- '/*'
  #
  #HelloWorldFunction:
    #Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    #Properties:
      #CodeUri: hello-world/
      #Handler: app.lambdaHandler
      #Runtime: nodejs22.x
      #Architectures:
      #- x86_64
      #Events:
        #HelloWorld:
          #Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          #Properties:
            #Path: /hello
            #Method: get

  #ApplicationResourceGroup:
    #Type: AWS::ResourceGroups::Group
    #Properties:
      #Name:
        #Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      #ResourceQuery:
        #Type: CLOUDFORMATION_STACK_1_0
  #ApplicationInsightsMonitoring:
    #Type: AWS::ApplicationInsights::Application
    #Properties:
      #ResourceGroupName:
        #Ref: ApplicationResourceGroup
      #AutoConfigurationEnabled: 'true'

#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #HelloWorldApi:
    #Description: API Gateway endpoint URL for Prod stage for Hello World function
    #Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  #HelloWorldFunction:
    #Description: Hello World Lambda Function ARN
    #Value: !GetAtt HelloWorldFunction.Arn
  #HelloWorldFunctionIamRole:
    #Description: Implicit IAM Role created for Hello World function
    #Value: !GetAtt HelloWorldFunctionRole.Arn
